### PR TITLE
I signed the assemblies so they can be referenced from other signed assemblies

### PR DESCRIPTION
**Pull request by Sicos1977**
I signed the assemblies so they can be referenced from other signed assemblies.
Unsigned assemblies can always add signed assemblies but not the other way around

### CODE REVIEW

**Comment by knuppe** [comment]
There was a long and controversial discussion about signing nuget packages over the internet... I'm reading a bit more to try to understand better the problem. Unfortunately, it's not a simple answer...

**Comment by Sicos1977** [comment]
You are not signing the nuget package but the SharpNL.net assembly. 

See this Microsoft link for more informatiion --> https://msdn.microsoft.com/en-us/library/xwb8f617(v=vs.110).aspx

**Comment by knuppe** [comment]
I know Kees, this subject is a bit [complicated](http://blog.nuget.org/20150203/package-signing.html)... 

But the good practices say we should sign the library in order to give thrust and use with GAC.
I'll try to sign and release a new nuget package with the lastast changes and library signed at sunday (or next week).

**Comment by knuppe** [comment]
Kees, I tried to sign the library... but can't be done.

In tests I need to use the version of opennlp via IKVM to test the compatibility of everything in SharpNL,  the opennlp is not signed, so I can't sign the library, otherwise I have to remove these tests and this unfortunately is not acceptable.

You can still sign the library in your side.

**Comment by Sicos1977** [comment]
What is the error you are getting? I forked your code and I can sign it without any problems... so I wonder what is different with the fork?

**Comment by knuppe** [comment]
`Assembly generation failed -- Referenced assembly 'opennlp-tools-1.6.0' does not have a strong name.`

**Pull request closed without merging**
